version: '3'
services:
  gateway:
    build: .
    container_name: gateway
    hostname: gateway
    volumes:
      - ./registry.yaml:/registry.yaml
    ports:
      - "9002:8000"
    environment:
      SERVICE_TIMEOUT: 5
      REGISTRY_PATH: /registry.yaml
