server:
  port: 8004
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
identity:
  clientId: gateway
  clientSecret: 09637506-a372-4380-a56b-ea1506e21dd2
  url: http://localhost:9001/auth
  realm: central-registry
  host: ${HOST:http://localhost:8004}
  userName: admin-user
  password: welcome
gateway:
  disableHttpOptionsMethod: true
  shareprofile:
    enable: false
  db:
    host: localhost
    port: 5432
    schema: gateway
    user: postgres
    password: password
    poolSize: 5
