server:
  port: 8000
gateway:
  #Valid values are guava(for local), redis
  cacheMethod: ${CACHE_METHOD:guava}
  redis:
    #Will not be used if cacheMethod is guava
    host: localhost
    port: 6379
    password: password
    expiry: 10
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
identity:
  clientId: gateway
  clientSecret: ${CLIENT_SECRET}
  url: http://localhost:9001/auth
  realm: central-registry
  host: ${HOST:http://localhost:8000}