server:
  port: 8000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
identity:
  clientId: gateway
  clientSecret: ${CLIENT_SECRET}
  url: http://localhost:9001/auth
  realm: central-registry
  host: ${HOST:http://localhost:8000}
gateway:
  db:
    host: localhost
    port: 5432
    schema: gateway
    user: postgres
    password: password
    poolSize: 5
